# Generated by Django 3.0.8 on 2020-07-02 05:53

from django.db import migrations, models
import django_jsonfield_backport.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JSONModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django_jsonfield_backport.models.JSONField()),
            ],
        ),
    ]
